Using Bootstrap: Newsweek Clone
yigitm/Newsweek pull request #2
Opened 2020-06-28 10:49 UTC by yigitm

> This project's goal is to make a mobile-first, responsive clone of the "Newsweek" web site. It is designed & built with a combination of Bootstrap 4 framework and HTML & CSS features.

**- Except for the specific sections/areas; I focused to give priority for using Bootstrap 4 CSS classes.**
**- Two main breakpoint is used for reponsive design: min-width: 768px. & min-width: 992px.**

Thank you so much for your time & inputs :raised_hands: .

2020-06-28 11:26 UTC, tirthajyoti-ghosh requested changes
# Status: Changes required 🛑

## Hello @yigitm 👋, you have done an incredible job making this project. It's one of the best projects I have seen so far 💯. Kudos for less relying on CSS 👌!

### However, there are a couple of changes that you need to work before we can merge.

-  The `search` in the navbar should not be a link. It should be an `input` element.

- You missed the `featured slideshows(us, world, tech & science, ...)` section after `editor's picks`.

#### Clone

![image](https://user-images.githubusercontent.com/57726348/85946006-1e52dc80-b95f-11ea-96b2-d173a39022b7.png)

#### Original

![image](https://user-images.githubusercontent.com/57726348/85946021-2f9be900-b95f-11ea-9dd5-49610b420fdd.png)

![image](https://user-images.githubusercontent.com/57726348/85946028-3cb8d800-b95f-11ea-9bba-0a4deff4e804.png)

![image](https://user-images.githubusercontent.com/57726348/85946038-4a6e5d80-b95f-11ea-87ad-78267a7441ff.png)

![image](https://user-images.githubusercontent.com/57726348/85946045-5a863d00-b95f-11ea-9e22-19a2bf481e39.png)


- In tablet mode, the social icons in `footer` are overflowing which is causing an extra space to appear to the right side of the clone.

#### The extra space -
![Annotation 2020-06-28 165430](https://user-images.githubusercontent.com/57726348/85946177-18a9c680-b960-11ea-82c4-bf1052c5b2ae.jpg)

#### The issue causing it - 
![Annotation 2020-06-28 165119](https://user-images.githubusercontent.com/57726348/85946153-ed26dc00-b95f-11ea-9d88-3d1873bb0dba.jpg)

- I have left one comment on your CSS code below. Be sure to check that.

2020-06-28 11:30 UTC, tirthajyoti-ghosh commented on style.css
> +  width: 25%;
There is a Bootstrap class for `width: 25%;` property. It is `w-25`. By removing this line and using the Bootstrap counterpart, you will further decrease your CSS code. Be sure to do that.

2020-06-28 11:34 UTC, tirthajyoti-ghosh requested changes
*I have noticed that you have added stickler config files but have not enabled stickler. Be sure to add stickler before your next code review. Even better, you can setup GHA. [Here](https://github.com/microverseinc/linters-config/tree/master/html-css) are the steps.*

Apply these changes and request another code review.

Happy coding 👨‍💻

2020-06-29 18:35 UTC, elmejdki requested changes
# Status: require changes :recycle: 
## Great job so far @yigitm :clap: you have made a great :tophat:  clone but in order to get it approved you need to make some minor changes :hammer: :wrench: :toolbox:.

- [x] Fix the header on mobile views it's overlapping:
![image](https://user-images.githubusercontent.com/34653764/86041449-91cb1b80-ba3d-11ea-81a0-822a76933141.png)

- [x] you have extras space above the culture & travel and also more stories on the desktop view, please remove it:
![image](https://user-images.githubusercontent.com/34653764/86041715-fc7c5700-ba3d-11ea-8fca-495b2da36e48.png)

- [x] on the opinion section you have cloned also some ads please remove them:
![image](https://user-images.githubusercontent.com/34653764/86042046-80364380-ba3e-11ea-9801-8da1eefecc8e.png)
![image](https://user-images.githubusercontent.com/34653764/86042066-87f5e800-ba3e-11ea-939a-7c0d251e0d70.png)
also this:
![image](https://user-images.githubusercontent.com/34653764/86042097-9217e680-ba3e-11ea-89ac-5c95d7e23702.png)
### :warning:  I recommend that you install ad-block as an extension for your browser.

- [x] please fix the subscribe section on mobile view, it's out of it' container:
![image](https://user-images.githubusercontent.com/34653764/86042312-ddca9000-ba3e-11ea-9ca5-fd3212fc3326.png)

- [x] also the form inside the opinion section:
![image](https://user-images.githubusercontent.com/34653764/86042371-f76bd780-ba3e-11ea-97d8-fb4c90b28224.png)

- [x] add some margin around the newsletter section:
![image](https://user-images.githubusercontent.com/34653764/86042446-12d6e280-ba3f-11ea-84ed-8175beff1dab.png)

### Please make all the required changes before you submit another code review.
# Happy Coding :tophat:

2020-06-30 13:04 UTC, elmejdki approved these changes
# status Approved :heavy_check_mark: 
## Great job guys, thank you for making the required changes :clap: 

now you can merge to master your project is approved.

## Happy Coding

2020-06-30 13:46 UTC, merged